<?php

/**
 * @file
 * Hook implementations and shared functions.
 */

/**
 * Implements hook_payment_amount_info().
 */
function payment_test_payment_amount_info() {
  return array(
    new PaymentAmountInfo(array(
      'callback' => 'payment_test_amount_extract',
      'name' => 'payment_test',
      'title' => t('Payment Form amount'),
    )),
  );
}

/**
 * Implements hook_payment_validate().
 */
function payment_test_payment_validate(Payment $payment, PaymentMethod $payment_method) {
  $payment->payment_test_payment_validate = TRUE;

  return TRUE;
}

/**
 * Implements hook_payment_status_change().
 */
function payment_test_payment_status_change(Payment $payment, $old_status) {
  $payment->payment_test_payment_status_change = TRUE;
}

/**
 * Implements hook_payment_pre_execute().
 */
function payment_test_payment_pre_execute(Payment $payment) {
  $payment->payment_test_payment_pre_execute = TRUE;
}

/**
 * Implements Payment finish callback.
 */
function payment_test_finish_callback() {}

/**
 * Implements PaymentAmount::callback.
 */
function payment_test_amount_extract($name, Payment $payment) {
  return(array($payment->amounts['foo'], $payment->amounts['bar']));
}