<?php

/**
 * @file
 *   Hook implementations and general functions.
 */

/**
 * Implements hook_menu().
 */
function paymentreference_menu() {
  $item['paymentreference/finish'] = array(
    'title' => 'Payment reference finished',
    'load arguments' => array('payment'),
    'page callback' => 'paymentreference_page_finish',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $item['paymentreference/pay/%paymentreference_instance/%/%'] = array(
    'load arguments' => array(3, 4),
    'title' => 'Add a payment reference',
    'title callback' => 'paymentreference_instance_title',
    'title arguments' => array(2),
    'page callback' => 'paymentreference_page',
    'page arguments' => array(2, 3, 4),
    'access callback' => 'paymentreference_instance_access',
    'access arguments' => array(2),
  );

  return $item;
}

/**
 * Implements hook_page_alter().
 */
function paymentreference_page_alter(&$page) {
  if (arg(0) == 'paymentreference') {
    $skip_regions = array_diff(element_children($page), array('content'));
    foreach ($skip_regions as $skip_region) {
      $page[$skip_region]['#access'] = FALSE;
    }
  }
}

/**
 * Implements menu wildcard loader to load a field instance.
 *
 * @param string $entity_type
 * @param string $bundle
 * @param string $field_name
 *
 * @return false|array
 */
function paymentreference_instance_load($entity_type, $bundle, $field_name) {
  $instance = field_info_instance($entity_type, $field_name, $bundle);

  return $instance ? $instance : FALSE;
}

/**
 * Check if the user has access to add a payment for a field instance.
 *
 * @param array $instance
 *
 * @return boolean
 */
function paymentreference_instance_access(array $instance) {
  global $user;

  // Check field permissions.
  if (!field_access('edit', field_info_field($instance['field_name']), $instance['entity_type'])) {
    return FALSE;
  }
  // Deny access if the user already has a payment available for this instance.
  if (paymentreference_load($instance['entity_type'], $instance['bundle'], $instance['field_name'], $user->uid)) {
    return FALSE;
  }
  return TRUE;
}

/**
 * Implements hook_field_info().
 */
function paymentreference_field_info() {
  $field['paymentreference'] = array(
    'label' => t('Payment reference'),
    'description' => t('Adds a reference to a payment.'),
    'instance_settings' => array(
      'amount' => 0,
      'currency_code' => 'XXX',
      'description' => '',
      'widget_description' => array(
        'value' => '',
        'format' => '',
      ),
    ),
    'default_widget' => 'paymentreference',
    'default_formatter' => 'paymentreference',
  );

  return $field;
}

/**
 * Implements hook_field_widget_info().
 */
function paymentreference_field_widget_info() {
  $widget['paymentreference'] = array(
    'label' => t('Payment reference'),
    'description' => t('Allows users to select existing unused payments, or to add a new payment on the fly.'),
    'field types' => array('paymentreference'),
    'behaviors' => array(
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
      'default value' => FIELD_BEHAVIOR_NONE,
    ),
  );

  return $widget;
}

/**
 * Implements hook_field_instance_settings_form().
 */
function paymentreference_field_instance_settings_form($field, $instance) {
  $form = array();

  if ($instance['widget']['type'] == 'paymentreference') {
    $form['currency_code'] = array(
      '#type' => 'select',
      '#title' => t('Currency'),
      '#options' => currency_api_get_list(),
      '#default_value' => $instance['settings']['currency_code'],
      '#required' => TRUE,
    );
    $form['amount'] = array(
      '#type' => 'paymentform_amount',
      '#title' => t('Amount'),
      '#default_value' => $instance['settings']['amount'],
      '#required' => TRUE,
      '#currency_code' => '',
    );
    $form['description'] = array(
      '#type' => 'textfield',
      '#title' => t('Payment description'),
      '#default_value' => $instance['settings']['description'],
      '#required' => TRUE,
    );
    $form['widget_description'] = array(
      '#type' => 'text_format',
      '#title' => t('Widget description'),
      '#default_value' => $instance['settings']['widget_description']['value'],
      '#format' => $instance['settings']['widget_description']['format'],
    );
  }

  return $form;
}

/**
 * Implements hook_field_widget_properties_alter().
 */
function paymentreference_field_widget_properties_alter(array &$widget, array $context) {
  // Store information in the widget that is not directly available in
  // hook_field_widget_form().
  $widget['paymentreference_entity'] = $context['entity'];
}

/**
 * Implements hook_field_widget_form().
 */
function paymentreference_field_widget_form(array &$form, array &$form_state, array $field, array $instance, $langcode, array $items, $delta, array $element) {
  global $user;

  if ($instance['widget']['type'] == 'paymentreference') {
    // Load the payment, either from the field value or from the table of
    // available payments.
    if ($pid = isset($items[$delta]['pid']) ? $items[$delta]['pid'] : 0) {
      $payment = entity_load_single('payment', $pid);
    }
    elseif ($payment = paymentreference_load($instance['entity_type'], $instance['bundle'], $instance['field_name'], $user->uid)) {
      $pid = $payment->pid;
    }

    $base = $element;

    // The field value (Payment ID).
    $element['pid'] = array(
      '#type' => 'value',
      '#value' => $pid,
      '#attached' => array(
        'js' => array(drupal_get_path('module', 'paymentreference') . '/js/paymentreference.js'),
      ),
    );

    // Description.
    $element['description'] = array(
      '#type' => 'item',
      '#markup' => check_markup($instance['settings']['widget_description']['value'], $instance['settings']['widget_description']['format']),
    ) + $base;

    // Payment information.
    $header = array(t('Amount'), t('Status'), t('Last updated'));
    if ($payment) {
      $row = array(
        payment_amount_human_readable($payment->totalAmount(TRUE, $payment->getLineItems('paymentreference')), $payment->currency_code),
        payment_status_info($payment->getStatus()->status, TRUE)->title,
        format_date($payment->getStatus()->created),
      );
      if (payment_access('view', $payment)) {
        $header[] = t('Operations');
        $row[] = t('<a href="@url" target="_blank">View payment details</a> (opens in a new window)', array(
          '@url' => url('payment/' . $payment->pid),
        ));
      }
    }
    else {
      $row = array(
        payment_amount_human_readable($instance['settings']['amount'], $instance['settings']['currency_code']),
        array(
          'data' => t('<a href="@url" target="_blank">Add a new payment</a> (opens in a new window)', array(
            '@url' => url('paymentreference/pay/' . $instance['entity_type'] . '/' . $instance['bundle'] . '/' . $instance['field_name']),
          )),
          'colspan' => 2,
        ),
      );
    }
    $table_id = drupal_html_id('paymentreference-payment-information');
    $element['payment'] = array(
      '#type' => 'markup',
      '#markup' => theme('table', array(
        'header' => $header,
        'rows' => array($row),
        'attributes' => array(
          'id' => $table_id,
        ),
      )),
      '#process' => array('paymentreference_field_widget_form_process'),
      '#paymentreference_delta' => $delta,
      '#paymentreference_field_name' => $instance['field_name'],
      '#attached' => array(
        'js' => array(
          array(
          'type' => 'setting',
            'data' => array(
              'PaymentreferencePaymentAvailable' => array(
                $table_id => !empty($pid),
              ),
            ),
          ),
        ),
      ),
    );

    // Refresh button.
    if (!$payment) {
      $element['refresh'] = array(
        '#type' => 'submit',
        '#value' => t('Re-check available payments'),
        '#submit' => array('paymentreference_field_widget_form_refresh_submit'),
        '#limit_validation_errors' => array(),
        '#ajax' => array(
          'callback' => 'paymentreference_field_widget_form_ajax_callback',
          'effect' => 'fade',
          'event' => 'mousedown',
          'wrapper' => $table_id,
          'progress' => array(),
        ),
        '#name' => 'paymentreference_refresh_' . $delta . '_' . $instance['field_name'],
        '#attributes' => array(
          'class' => array('paymentreference-refresh-button', 'js-hide')
        ),
      );
    }
  }

  return $element;
}

/**
 * Implements hook_field_validate().
 */
function paymentreference_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  global $user;

  if ($field['type'] == 'paymentreference') {
    foreach ($items as $delta => $item) {
      // Check if there is a value at all.
      if (empty($item['pid'])) {
        // Check if the value is required.
        if ($instance['required']) {
          $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => 'paymentreference_missing',
            'message' => t('Payment is required'),
          );
        }
        // There is no value to validate, so stop validation for this item.
        break;
      }

      // Check if this is an existing entity (which means it has an ID).
      $ids = entity_extract_ids($entity_type, $entity);
      if ($ids[0]) {
        // Check if the entity already has a value for this field and if it
        // equals the new value.
        $query = new EntityFieldQuery();
        $count = $query->fieldCondition($field['field_name'], 'pid', $item['pid'])
          ->count()
          ->execute();
        if ($count) {
          // The value hasn't changed, so stop validation for this item.
          break;
        }
      }

      $pid = $item['pid'];

      // Check if the selected payment is available for this user and this
      // reference.
      if (paymentreference_available($pid, $user->uid) === FALSE) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'paymentreference_invalid_pid',
          'message' => t('The selected payment does not exist or is not available.'),
        );
      }
    }
  }
}

/**
 * Implements hook_field_widget_error().
 */
function paymentreference_field_widget_error($element, $error, $form, &$form_state) {
  form_error($element, $error['message']);
}

/**
 * Implements hook_field_is_empty().
 */
function paymentreference_field_is_empty(array $item, array $field) {
  if ($field['type'] == 'paymentreference') {
    return empty($item['pid']);
  }
}

/**
 * Implements hook_field_insert().
 */
function paymentreference_field_insert($entity_type, $entity, array $field, array $instance, $langcode, array &$items) {
  if ($field['type'] == 'paymentreference') {
    foreach ($items as $item) {
      paymentreference_delete($item['pid']);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_ACTION().
 */
function paymentreference_payment_insert(Payment $payment) {
  if (!empty($payment->context_data['paymentreference'])) {
    paymentreference_insert($payment->context_data['entity_type'], $payment->context_data['bundle'], $payment->context_data['field_name'], $payment->pid);
  }
}

/**
 * Check if a payment is available for referencing.
 *
 * @param integer $pid
 *   The PID of the payment to check.
 * @param integer $uid
 *   The UID of the user that should be the payment's owner.
 *
 * @return false|array
 *   FALSE if the payment is not available. Otherwise an array with keys
 *   "entity_type", "bundle", and "field_name" to identify the instance with
 *   the payment is for.
 */
function paymentreference_available($pid, $uid) {
  $query = db_select('paymentreference', 'pr');
  $query->addJoin('INNER', 'payment', 'p', 'p.pid = pr.pid');

  return $query->fields('pr', array('entity_type', 'bundle', 'field_name'))
    ->condition('pr.pid', $pid)
    ->condition('uid', $uid)
    ->execute()
    ->fetchAssoc();
}

/**
 * Load a Payment available for referencing through an instance.
 *
 * @param string $entity_type
 *   The entity_type for which the payment should be available.
 * @param string $bundle
 *   The bundle of $entity_type for which the payment should be available.
 * @param string $field_name
 *   The name of the field on $bundle for which the payment should be
 *   available.
 * @param integer $uid
 *   The UID of the user for whom the payment should be available.
 *
 * @return false|Payment
 */
function paymentreference_load($entity_type, $bundle, $field_name, $uid) {
  $query = db_select('paymentreference', 'pr');
  $query->addJoin('INNER', 'payment', 'p', 'p.pid = pr.pid');
  $query->fields('pr', array('pid'))
    ->condition('entity_type', $entity_type)
    ->condition('bundle', $bundle)
    ->condition('field_name', $field_name)
    ->condition('uid', $uid);
  $pid = $query->execute()->fetchField();

  return $pid ? entity_load_single('payment', $pid) : FALSE;
}

/**
 * Insert a Payment available for referencing through a field instance.
 *
 * @param string $entity_type
 *   The entity_type for which the payment is available.
 * @param string $bundle
 *   The bundle of $entity_type for which the payment is available.
 * @param string $field_name
 *   The name of the field on $bundle for which the payment is available.
 * @param integer $pid
 *   The PID of the available payment.
 *
 * @return integer
 *   SAVED_NEW
 */
function paymentreference_insert($entity_type, $bundle, $field_name, $pid) {
  $data = array(
    'entity_type' => $entity_type,
    'bundle' => $bundle,
    'field_name' => $field_name,
    'pid' => $pid,
  );

  return drupal_write_record('paymentreference', $data);
}

/**
 * Delete a Payment available for referencing.
 *
 * @param integer $pid
 */
function paymentreference_delete($pid) {
  db_delete('paymentreference')
    ->condition('pid', $pid)
    ->execute();
}

/**
 * Return the page title for a field instance.
 *
 * @param array $instance
 *
 * @return string
 */
function paymentreference_instance_title(array $instance) {
  return $instance['label'];
}

/**
 * Return a payment page for a field instance.
 *
 * @param array $instance
 *
 * @return array
 *   A Drupal build array.
 */
function paymentreference_page(array $instance) {
  $payment = new Payment(array(
    'context_data' => array(
      'paymentreference' => TRUE,
      'entity_type' => $instance['entity_type'],
      'bundle' => $instance['bundle'],
      'field_name' => $instance['field_name'],
    ),
    'currency_code' => $instance['settings']['currency_code'],
    'finish_callback' => 'paymentreference_payment_finish',
  ));
  // @todo Description should be US English, but can be anything.
  $payment->setLineItem(new PaymentLineItem(array(
    'amount' => $instance['settings']['amount'],
    'description' => $instance['settings']['description'],
    'name' => 'paymentreference',
  )));

  return drupal_get_form('payment_form_standalone', $payment);
}

/**
 * Implements Payment::finish_callback.
 */
function paymentreference_payment_finish(Payment $payment) {
  $_SESSION['paymentreference_pid'] = $payment->pid;
  drupal_goto('paymentreference/finish');
}

/**
 * Menu page callback to call after a payment reference payment has finished.
 *
 * @return integer|array
 */
function paymentreference_page_finish() {
  if (isset($_SESSION['paymentreference_pid'])) {
    // Assign the PID to the local scope and remove it from the session.
    $pid = $_SESSION['paymentreference_pid'];
    unset($_SESSION['paymentreference_pid']);

    // Load the payment and the instance it's for, and build the page.
    if ($payment = entity_load_single('payment', $pid)) {
      $instance_info = paymentreference_available($pid, $payment->uid);
      $instance = field_info_instance($instance_info['entity_type'], $instance_info['field_name'], $instance_info['bundle']);
      drupal_set_title($instance['label']);
      return array(
        '#type' => 'markup',
        '#markup' => t('Your payment is %status. You can now <span class="paymentreference-window-close">close this window</span>.', array(
          '%status' => payment_status_info($payment->getStatus()->status, TRUE)->title,
        )),
        '#attached' => array(
          'js' => array(drupal_get_path('module', 'paymentreference') . '/js/paymentreference.js'),
        ),
      );
    }
  }
  return MENU_ACCESS_DENIED;
}

/**
 * Implements form submit callback for paymentreference_field_widget_form().
 */
function paymentreference_field_widget_form_refresh_submit(array $form, array &$form_state) {
  $form_state['rebuild'] = TRUE;
}

/**
 * Implements hook_field_access().
 */
function paymentreference_field_access($op, $field, $entity_type, $entity, $account) {
  global $user;

  if ($field['type'] == 'paymentreference') {
    return !empty($user->uid);
  }
  return TRUE;
}

/**
 * Return a payment method controller's form elements to configure a payment.
 */
function paymentreference_field_widget_form_ajax_callback(array $form, array &$form_state) {
  return drupal_array_get_nested_value($form, $form_state[$form_state['triggering_element']['#name']]);
}

function paymentreference_field_widget_form_process(array $element, array &$form_state, array &$form) {
  $form_state['paymentreference_refresh_' . $element['#paymentreference_delta'] . '_' . $element['#paymentreference_field_name']] = $element['#parents'];

  return $element;
}